

class OpMultiplayer():
    OP_ACTIONS_LOGIN = "OP_ACTIONS_LOGIN"
    OP_ACCEPT = "OP_SEND_ACCEPT"
    OP_ADDUSER = "OP_SEND_ADDUSER"
    OP_ACTIONS_CONFIRMPLAYERSTART = "OP_ACTIONS_CONFIRMPLAYERSTART"
    OP_START = "OP_SEND_START"
    OP_ACTIONS_MOVEPLAYER = "OP_ACTIONS_MOVEPLAYER"
    OP_UPDATEPLAYER = "OP_SEND_UPDATEPLAYER"
    OP_ACTIONS_KILLPLAYER = "OP_ACTIONS_KILLPLAYER"
    OP_ACTIONS_EXITLAYER = "OP_ACTIONS_EXITLAYER"
    OP_KILLPLAYER = "OP_SEND_KILLPLAYER"
    OP_END = "OP_SEND_END"
    OP_EXIT = "OP_SEND_EXIT"
    OP_SHOOT = "OP_SEND_SHOOT"